services:
  web:
    build: .
    image: campfire-local:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    env_file: .env
    environment:
      - DISABLE_SSL=true
      - SKIP_TELEMETRY=true
    volumes:
      - campfire:/rails/storage

volumes:
  campfire:
